// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ArmAndRun(arg1:string,arg2:boolean):Promise<void>;

export function CreateOpenSeaTasks(arg1:main.OpenSeaTaskInput):Promise<Array<main.MintTask>>;

export function CreateTask(arg1:main.MintTask):Promise<main.MintTask>;

export function Dashboard():Promise<main.Dashboard>;

export function ImportMnemonic(arg1:string,arg2:string,arg3:number):Promise<Array<string>>;

export function ImportPrivateKey(arg1:string,arg2:string):Promise<string>;

export function InspectOpenSeaDrop(arg1:string):Promise<main.OpenSeaDrop>;

export function SetTaskEnabled(arg1:string,arg2:boolean):Promise<void>;

export function StopRunner():Promise<void>;
