// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArmAndRun(arg1, arg2) {
  return window['go']['main']['App']['ArmAndRun'](arg1, arg2);
}

export function CreateOpenSeaTasks(arg1) {
  return window['go']['main']['App']['CreateOpenSeaTasks'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function Dashboard() {
  return window['go']['main']['App']['Dashboard']();
}

export function DeleteCollectionTasks(arg1, arg2) {
  return window['go']['main']['App']['DeleteCollectionTasks'](arg1, arg2);
}

export function GenerateMnemonicWallets(arg1, arg2) {
  return window['go']['main']['App']['GenerateMnemonicWallets'](arg1, arg2);
}

export function ImportMnemonic(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportMnemonic'](arg1, arg2, arg3);
}

export function ImportPrivateKey(arg1, arg2) {
  return window['go']['main']['App']['ImportPrivateKey'](arg1, arg2);
}

export function ImportPrivateKeys(arg1, arg2) {
  return window['go']['main']['App']['ImportPrivateKeys'](arg1, arg2);
}

export function InspectOpenSeaDrop(arg1) {
  return window['go']['main']['App']['InspectOpenSeaDrop'](arg1);
}

export function SetCollectionTasksEnabled(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCollectionTasksEnabled'](arg1, arg2, arg3);
}

export function SetTaskEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetTaskEnabled'](arg1, arg2);
}

export function StopRunner() {
  return window['go']['main']['App']['StopRunner']();
}
